openapi: 3.0.0
info:
  title: 'Customer Operations'
  version: 1.0.0
paths:
  /customers:
    get:
      tags:
        - Customers
      summary: 'Get all customers'
      operationId: 94eabb9a66b57dc9565cbcdb81d66dd6
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  customers: { type: array, items: { $ref: '#/components/schemas/CustomerResource' } }
                type: object
    post:
      tags:
        - Customers
      summary: 'Create new customer'
      operationId: e12681ada60534c3a4f9666599eb5887
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: 'Customer Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResource'
        '400':
          description: 'Check the sended data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResource'
        '500':
          description: 'Customer creation failed'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResource'
  '/customers/{customerId}':
    get:
      tags:
        - Customers
      summary: 'Get a customer by ID'
      operationId: bbd18e8e02af7597575794ab70fca80f
      parameters:
        -
          name: customerId
          in: path
          description: 'ID of the customer to get'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResource'
        '404':
          description: 'Customer not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResource'
    put:
      tags:
        - Customers
      summary: 'Update existing customer'
      operationId: fd9e6d2245eef2cf78272c1140c0305a
      parameters:
        -
          name: customerId
          in: path
          description: 'ID of the customer to update'
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResource'
        '400':
          description: 'Check the sended data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResource'
        '404':
          description: 'Customer not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResource'
        '500':
          description: 'Customer update failed'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResource'
    delete:
      tags:
        - Customers
      summary: 'Delete customer'
      operationId: 1409f3779fdeaa9dda1ae7a38ba7824b
      parameters:
        -
          name: customerId
          in: path
          description: 'ID of the customer to delete'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success
        '404':
          description: 'Customer not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResource'
        '500':
          description: 'Customer deletion failed'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResource'
components:
  schemas:
    Date:
      properties:
        date:
          description: Timestamps
          type: string
          example: '2023-04-27 23:46:29.000000'
        timezone_type:
          description: 'Timezone type'
          type: string
          example: '3'
        timezone:
          description: Timezone
          type: string
          example: America/Sao_Paulo
      type: object
    ErrorResource:
      properties:
        status:
          description: 'HTTP Status'
          type: integer
        code:
          description: 'Error Code'
          type: integer
        message:
          description: 'Error messages'
          type: array
          items:
            properties:
              field:
                type: string
                example: 'Error message'
            type: object
      type: object
    Customer:
      required:
        - name
        - email
        - phone
      properties:
        name:
          description: 'Customer name'
          type: string
          example: 'John Doe'
        email:
          description: 'Customer email address'
          type: string
          uniqueItems: true
          example: johndoe@example.com
        phone:
          description: 'Customer phone number'
          type: string
          uniqueItems: true
          example: '5511954136548'
      type: object
    CustomerResource:
      properties:
        customer:
          description: 'Customer Data'
          properties:
            id:
              description: 'Customer ID'
              type: integer
              example: '1'
            name:
              description: 'Customer name'
              type: string
              example: 'John Doe'
            email:
              description: 'Customer email address'
              type: string
              example: johndoe@example.com
            phone:
              description: 'Customer phone number'
              type: string
              example: '5511954136548'
            created_at:
              $ref: '#/components/schemas/Date'
            updated_at:
              $ref: '#/components/schemas/Date'
            deleted_at:
              description: 'Date of deletion of customer'
              type: object
              example: null
          type: object
      type: object
